config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-reporting:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-reporting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-lime-deer.sh
        container: qc.acc_bumpy-chocolate-pig
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tomato-bonobo.sh
        container: qc.doc_hazy-myrtle-mandrill
      github.com/eosc-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-wisteria-mayfly.sh
        container: qc.doc_goopy-linen-lion
      github.com/eosc-synergy/sqaaas-reporting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-fuchsia-ocelot.sh
        container: qc.doc_leaky-salmon-rhinoceros
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-reporting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-harlequin-rat.sh
        container: qc.lic_woozy-teal-bee
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-reporting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.messy-yellow-frise.sh
        container: qc.met_skanky-brass-iguana
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-reporting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-emerald-elephant.sh
        container: qc.sec_homely-denim-zorse
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-reporting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-turquoise-serval.sh
        container: qc.sty_woolly-linen-reindeer
      github.com/eosc-synergy/sqaaas-reporting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-amethyst-gerbil.sh
        container: qc.sty_flaky-cerise-hornet
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-reporting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homely-magnolia-seal.sh
        container: qc.uni_skinny-sepia-guppy
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-reporting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-platinum-cheetah.sh
        container: qc.ver_pokey-celadon-beetle
timeout: 5400
