config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-reporting:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-reporting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-pear-eleuth.sh
        container: qc.acc_zippy-amaranth-eel
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ivory-jackal.sh
        container: qc.doc_hasty-black-reindeer
      github.com/eosc-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-charcoal-chicken.sh
        container: qc.doc_hasty-asparagus-saola
      github.com/eosc-synergy/sqaaas-reporting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cerulean-monster.sh
        container: qc.doc_lanky-goldenrod-peccary
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-reporting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-champagne-slug.sh
        container: qc.lic_flaky-azure-giraffe
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-reporting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-emerald-echidna.sh
        container: qc.met_crabby-cornflower-labradoodle
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-reporting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-grey-civet.sh
        container: qc.sec_woozy-indigo-dog
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-reporting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ruby-goat.sh
        container: qc.sty_squeaky-blue-slug
      github.com/eosc-synergy/sqaaas-reporting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-mustard-bongo.sh
        container: qc.sty_clammy-saffron-avocet
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-reporting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-saffron-dhole.sh
        container: qc.uni_woolly-harlequin-duck
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-reporting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-wisteria-macaque.sh
        container: qc.ver_skimpy-lemon-affenpinscher
timeout: 5400
