config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-reporting:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-reporting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-amaranth-uguisu.sh
        container: qc.acc_geeky-olivine-coyote
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-pink-mouse.sh
        container: qc.doc_snappy-chartreuse-leopard
      github.com/eosc-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-gamboge-spitz.sh
        container: qc.doc_frumpy-yellow-mastiff
      github.com/eosc-synergy/sqaaas-reporting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cardinal-coati.sh
        container: qc.doc_tasty-grey-jellyfish
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-reporting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-linen-bobcat.sh
        container: qc.lic_droopy-persimmon-shrimp
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-reporting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-emerald-dachsbracke.sh
        container: qc.met_chewy-coral-owl
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-reporting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-fuchsia-corgi.sh
        container: qc.sec_paltry-dandelion-mayfly
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-reporting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-olivine-toad.sh
        container: qc.sty_randy-eggplant-bird
      github.com/eosc-synergy/sqaaas-reporting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cinnamon-hare.sh
        container: qc.sty_seedy-blue-oyster
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-reporting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-azure-paradise.sh
        container: qc.uni_thirsty-indigo-collie
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-reporting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lilac-salamander.sh
        container: qc.ver_gummy-violet-urchin
timeout: 5400
