config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-reporting:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-reporting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-sapphire-hare.sh
        container: qc.acc_droopy-fuchsia-spitz
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-gamboge-kangaroo.sh
        container: qc.doc_goopy-saffron-tang
      github.com/eosc-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-periwinkle-tetra.sh
        container: qc.doc_snappy-periwinkle-frise
      github.com/eosc-synergy/sqaaas-reporting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-bistre-buzzard.sh
        container: qc.doc_hazy-lilac-bison
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-reporting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-tan-angora.sh
        container: qc.lic_gamy-tomato-booby
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-reporting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-platinum-hyrax.sh
        container: qc.met_sloppy-ochre-starfish
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-reporting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-linen-bird.sh
        container: qc.sec_fuzzy-myrtle-sheepdog
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-reporting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.silly-periwinkle-termite.sh
        container: qc.sty_gimpy-smalt-bullfrog
      github.com/eosc-synergy/sqaaas-reporting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-platinum-dogfish.sh
        container: qc.sty_randy-olive-rottweiler
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-reporting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cerulean-gecko.sh
        container: qc.uni_gummy-smalt-capybara
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-reporting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-olive-chimpanzee.sh
        container: qc.ver_hazy-aquamarine-duck
timeout: 5400
