config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-reporting:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-reporting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-lavender-bracke.sh
        container: qc.acc_trippy-mauve-seal
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-ecru-wildebeest.sh
        container: qc.doc_cheeky-sapphire-cassowary
      github.com/EOSC-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-taupe-crane.sh
        container: qc.doc_seedy-indigo-barb
      github.com/EOSC-synergy/sqaaas-reporting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-azure-turkey.sh
        container: qc.doc_freaky-magenta-clam
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-zucchini-dalmatian.sh
        container: qc.lic_sleazy-alizarin-worm
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-saffron-horse.sh
        container: qc.met_smelly-crimson-mammoth
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ecru-robin.sh
        container: qc.sec_cheeky-carmine-robin
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-ecru-macaque.sh
        container: qc.sty_goopy-ivory-dragon
      github.com/EOSC-synergy/sqaaas-reporting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-vermilion-rattlesnake.sh
        container: qc.sty_pokey-charcoal-tarantula
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-goldenrod-pinscher.sh
        container: qc.uni_woolly-lime-giraffe
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-lavender-lemur.sh
        container: qc.ver_hasty-pear-fox
timeout: 5400
