config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-reporting:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-reporting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-orchid-lion.sh
        container: qc.acc_cloudy-scarlet-mau
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-persimmon-whale.sh
        container: qc.doc_slaphappy-copper-drever
      github.com/EOSC-synergy/sqaaas-reporting git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-mustard-rattlesnake.sh
        container: qc.doc_stealthy-charcoal-binturong
      github.com/EOSC-synergy/sqaaas-reporting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-chocolate-cat.sh
        container: qc.doc_cozy-ultramarine-bonobo
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-black-mole.sh
        container: qc.lic_geeky-amethyst-gerbil
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-sapphire-civet.sh
        container: qc.met_shabby-dandelion-angora
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-rust-cichlid.sh
        container: qc.sec_boozy-pumpkin-frise
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-goldenrod-greyhound.sh
        container: qc.sty_messy-violet-caterpillar
      github.com/EOSC-synergy/sqaaas-reporting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-ecru-tetra.sh
        container: qc.sty_freaky-olive-capybara
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-teal-mayfly.sh
        container: qc.uni_snippy-amethyst-quokka
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-turquoise-rhinoceros.sh
        container: qc.ver_messy-thistle-barnacle
timeout: 5400
